import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "./context/UserContext";
import { geistSans, geistMono } from "./fonts"; // ✅ apenas importe, não exporte

export const metadata: Metadata = {
	title: "Aluga Ai",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<UserProvider>{children}</UserProvider>
			</body>
		</html>
	);
}
